load-dtbo:
	@sudo mkdir /sys/kernel/config/device-tree/overlays/imx519
	@sudo cp imx519.dtbo /sys/kernel/config/device-tree/overlays/imx519/dtbo
	@sudo cp imx519.dtbo /sys/kernel/config/device-tree/overlays/imx519/dtbo
